'use strict';

import * as path from 'path';

import { commands, workspace, Disposable, ExtensionContext } from 'vscode';
import { LanguageClient, LanguageClientOptions, ServerOptions, TransportKind } from 'vscode-languageclient';

export function activate(context: ExtensionContext) {

	// Node server module
	let serverModule = context.asAbsolutePath(path.join('server', 'server.js'));
	
	//Use debug options for the debug mode
	let debugOptions = { execArgv: ["--nolazy", "--inspect=9229"] };
	let serverOptions: ServerOptions = {
		run : { module: serverModule, transport: TransportKind.ipc },
		debug: { module: serverModule, transport: TransportKind.ipc, options: debugOptions }
	}
	
	let clientOptions: LanguageClientOptions = {
		// Register the server for Cucumber feature files
		documentSelector: ['feature'],
		synchronize: {
			configurationSection: 'cucumberautocomplete',
			// Notify the server about file changes to '.clientrc files contain in the workspace
			fileEvents: workspace.createFileSystemWatcher('**/.clientrc')
		}
	}

	// Register our keyboard shortcut for gherkin help lookup. This takes selected text and feeds it
	// into the javascript based search engine in our autogenerated documentation.
	let disposableCommand = commands.registerTextEditorCommand ('gherkinHelpLookup', editor => {
		// We need to get the characters which are currently selected. The keybinding is set up such
		// that it will only work if the editor has currently selected text. Replace all spaces with
		// "+" characters for the URL encoding.
		const searchText = editor.document.getText(editor.selection).replace(' ', '+');
		// Compose the URL to feed to the sharepoint help page javascript search page
		const searchURL = 'http://intranet/sites/Development/area/software/services/PET/Shared%20Documents/Steps_Docs/search.html?q=' + searchText;
		// Open the page by executing the URL as a command: use opnfor this. The system will open the URL in
		// the default browser for the Windows machine (this extension is designed for use with windows only).
		const opn = require('opn');
		// opn(searchURL, { app: args });
		opn(searchURL);
	} )
	
	// Create the language client and start the client.
	let disposable = new LanguageClient('gherkinautocomplete-client', 'Gherkin auto complete plugin', serverOptions, clientOptions).start();
	
	//Client will be deactivate on extension deactivation
	context.subscriptions.push(disposable);
}
